---

# Provision the infrastructure using Terraform
- name: Provision infrastructure
  hosts: openstack
  pre_tasks:
    # We need to convert the floating IP id to an address for Terraform
    - name: Look up floating IP
      include_role:
        name: stackhpc.terraform-infra
        tasks_from: lookup_floating_ip
      vars:
        os_floating_ip_id: "{{ cluster_floating_ip }}"
  roles:
    - role: stackhpc.terraform-infra
      vars:
        # Variables controlling the Terraform provisioning
        terraform_project_path: "{{ playbook_dir }}/terraform"
        terraform_state: "{{ cluster_state | default('present') }}"
        terraform_variables:
          cluster_name: "{{ cluster_name }}"
          cluster_network: "{{ cluster_network }}"
          cluster_floating_ip: "{{ os_floating_ip_info.floating_ip_address }}"
          # We need to inject the user's SSH key and the deploy key for the cluster
          cluster_ssh_public_keys: "{{ [cluster_deploy_ssh_public_key, cluster_user_ssh_public_key] | to_json }}"
          server_image: "{{ cluster_image }}"
          server_flavor: "{{ minio_server_flavor }}"

- hosts: cluster
  become: yes
  pre_tasks:
    # The Minio role doesn't play nice with SELinux
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
  roles:
    - minio
  vars:
    minio_hostname: "{{ ansible_default_ipv4.address }}"
    minio_home: /var/lib/minio
    minio_enable_ssl: false
